### ISSUE TITLE
StatefulSolver vs GenericSolverWidening

### ISSUE THREAD

**Issue by altineel** [aqtech-ca/mcts4py#12]
In the StatefulSolver.action() method, the simulate_action() method is not called while it is the case in GenericSolverWidening. Why is there such a difference ?

**Comment by larkz** [comment]
I'm not sure where `GenericSolverWidening` is from, can you elaborate?

**Comment by altineel** [comment]
Sorry, it is the copy of GenericSolver, that I created to implement ProgresiveWidening. Nevertheless, you can check StatefulSolver against GenericSolver. And it is not the action() method. But **select()** method. There is no _simulate_action()_ call at the end of StatefulSolver.select().

**Comment by larkz** [comment]
`simulate_action` only belongs to `GenericSolver`. Because in `GenericSolver` the state is not tracked, only a sequence of actions, therefore a simulation needs to be run to determine the state and properties of that state. In `StatefulSolver`, state  and state properties are explicitly tracked and re-simulation is not required.
